#!/bin/bash

#############################################
# Model Integration Verification Script
# Verifies that trained model is used by backend
#############################################

echo "============================================================"
echo "  Model Integration Verification"
echo "============================================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if model file exists
MODEL_FILE="models/simple_ml_model.pkl"

echo "Step 1: Checking model file..."
if [ -f "$MODEL_FILE" ]; then
    MODEL_SIZE=$(du -h "$MODEL_FILE" | cut -f1)
    MODEL_DATE=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" "$MODEL_FILE" 2>/dev/null || stat -c "%y" "$MODEL_FILE" 2>/dev/null | cut -d'.' -f1)

    print_success "Model file found: $MODEL_FILE"
    echo "   Size: $MODEL_SIZE"
    echo "   Modified: $MODEL_DATE"
else
    print_error "Model file NOT found: $MODEL_FILE"
    echo ""
    print_info "To train the model, run:"
    echo "   python ml/phishing_ml_model.py"
    echo ""
    exit 1
fi

echo ""
echo "Step 2: Verifying model can be loaded..."

# Test loading the model
python3 -c "
import sys
import os
sys.path.insert(0, '.')

try:
    from ml.simple_ml_model import SimplePhishingML
    ml_model = SimplePhishingML()
    ml_model.load_model('$MODEL_FILE')
    print('✅ Model loaded successfully')
    print(f'   Version: {ml_model.model_version}')
    print(f'   RF model: {ml_model.rf_model}')
    print(f'   TF-IDF vectorizer: {ml_model.tfidf_vectorizer}')
except Exception as e:
    print(f'❌ Error loading model: {e}')
    sys.exit(1)
"

if [ $? -eq 0 ]; then
    print_success "Model loads correctly"
else
    print_error "Model failed to load"
    exit 1
fi

echo ""
echo "Step 3: Testing model prediction..."

# Test prediction
python3 -c "
import sys
sys.path.insert(0, '.')

try:
    from ml.simple_ml_model import SimplePhishingML

    # Load model
    ml_model = SimplePhishingML()
    ml_model.load_model('$MODEL_FILE')

    # Test email data
    test_email = {
        'subject': 'URGENT: Verify your account',
        'body': 'Click here to verify your account immediately or it will be suspended.',
        'sender': 'phishing@badsite.tk'
    }

    # Make prediction
    prediction, probabilities = ml_model.predict(test_email)

    print('✅ Prediction successful')
    print(f'   Input: \"{test_email[\"subject\"]}\"')
    print(f'   Result: {\"Phishing\" if prediction == 1 else \"Legitimate\"}')
    print(f'   Confidence: {probabilities[1] * 100:.2f}%')

except Exception as e:
    print(f'❌ Prediction failed: {e}')
    import traceback
    traceback.print_exc()
    sys.exit(1)
"

if [ $? -eq 0 ]; then
    print_success "Model prediction works"
else
    print_error "Model prediction failed"
    exit 1
fi

echo ""
echo "Step 4: Checking backend integration..."

# Check if backend file has ML loading code
if grep -q "ml_model.load_model" backend/app.py; then
    print_success "Backend has ML model loading code"
else
    print_warning "Backend may not load ML model correctly"
fi

# Check if backend uses ML prediction
if grep -q "ml_model.predict" backend/app.py; then
    print_success "Backend uses ML model for predictions"
else
    print_warning "Backend may not use ML predictions"
fi

echo ""
echo "============================================================"
print_success "VERIFICATION COMPLETE!"
echo "============================================================"
echo ""
echo "Summary:"
echo "  ✅ Model file exists and is valid"
echo "  ✅ Model can be loaded successfully"
echo "  ✅ Model can make predictions"
echo "  ✅ Backend is configured to use the model"
echo ""
print_info "The model generated by train_and_save() will be used automatically"
print_info "when you upload emails through the backend API."
echo ""
print_info "To verify in production:"
echo "  1. Start backend: python backend/app.py"
echo "  2. Look for: '🤖 ML MODEL LOADED' message"
echo "  3. Upload an email via the web interface"
echo "  4. Check console for: 'ML Prediction: ...' output"
echo ""
echo "============================================================"
